{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyP5FbZzBoHCQ+BGU5Ft4rKF",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/dayaleroro/Gestion_de_proyectos/blob/main/Untitled32.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 2,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "svyo7Xu-7yF1",
        "outputId": "19609aa9-a347-4384-c9f9-7a5b3587533b"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Collecting streamlit\n",
            "  Downloading streamlit-1.49.1-py3-none-any.whl.metadata (9.5 kB)\n",
            "Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (5.24.1)\n",
            "Requirement already satisfied: altair!=5.4.0,!=5.4.1,<6,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)\n",
            "Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)\n",
            "Requirement already satisfied: cachetools<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.2)\n",
            "Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.2.1)\n",
            "Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)\n",
            "Requirement already satisfied: packaging<26,>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (25.0)\n",
            "Requirement already satisfied: pandas<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.2)\n",
            "Requirement already satisfied: pillow<12,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)\n",
            "Requirement already satisfied: protobuf<7,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.5)\n",
            "Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)\n",
            "Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)\n",
            "Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.5.0)\n",
            "Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)\n",
            "Requirement already satisfied: typing-extensions<5,>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)\n",
            "Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)\n",
            "Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.45)\n",
            "Collecting pydeck<1,>=0.8.0b4 (from streamlit)\n",
            "  Downloading pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)\n",
            "Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.4.2)\n",
            "Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.1.6)\n",
            "Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (4.25.1)\n",
            "Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2.2.0)\n",
            "Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)\n",
            "Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)\n",
            "Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)\n",
            "Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)\n",
            "Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.3)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.10)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2025.8.3)\n",
            "Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.2)\n",
            "Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.0.2)\n",
            "Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (25.3.0)\n",
            "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2025.4.1)\n",
            "Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.36.2)\n",
            "Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.27.0)\n",
            "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)\n",
            "Downloading streamlit-1.49.1-py3-none-any.whl (10.0 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m10.0/10.0 MB\u001b[0m \u001b[31m61.4 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m6.9/6.9 MB\u001b[0m \u001b[31m116.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hInstalling collected packages: pydeck, streamlit\n",
            "Successfully installed pydeck-0.9.1 streamlit-1.49.1\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "2025-09-04 13:41:33.129 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-09-04 13:41:33.130 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-09-04 13:41:33.267 \n",
            "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
            "  command:\n",
            "\n",
            "    streamlit run /usr/local/lib/python3.12/dist-packages/colab_kernel_launcher.py [ARGUMENTS]\n",
            "2025-09-04 13:41:33.268 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-09-04 13:41:33.270 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-09-04 13:41:33.275 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-09-04 13:41:33.276 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-09-04 13:41:33.276 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-09-04 13:41:33.278 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-09-04 13:41:33.279 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-09-04 13:41:33.280 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-09-04 13:41:33.281 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-09-04 13:41:33.282 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-09-04 13:41:33.283 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-09-04 13:41:33.284 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-09-04 13:41:33.284 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-09-04 13:41:33.285 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-09-04 13:41:33.286 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-09-04 13:41:33.287 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-09-04 13:41:33.288 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-09-04 13:41:33.289 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-09-04 13:41:33.290 Session state does not function when running a script without `streamlit run`\n",
            "2025-09-04 13:41:33.290 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-09-04 13:41:33.291 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-09-04 13:41:33.292 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-09-04 13:41:33.294 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-09-04 13:41:33.294 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-09-04 13:41:33.295 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-09-04 13:41:33.296 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-09-04 13:41:33.296 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-09-04 13:41:33.297 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
          ]
        }
      ],
      "source": [
        "!pip install streamlit plotly\n",
        "import streamlit as st\n",
        "import pandas as pd\n",
        "import plotly.express as px\n",
        "\n",
        "# -----------------------------\n",
        "# CONFIGURACIÓN DE LA PÁGINA\n",
        "# -----------------------------\n",
        "st.set_page_config(page_title=\"Proyecto Educación Rural con IA\", page_icon=\"📊\", layout=\"wide\")\n",
        "\n",
        "# -----------------------------\n",
        "# ESTILOS CSS PERSONALIZADOS\n",
        "# -----------------------------\n",
        "st.markdown(\"\"\"\n",
        "    <style>\n",
        "    .card {\n",
        "        background-color: #f9f9f9;\n",
        "        padding: 20px;\n",
        "        border-radius: 15px;\n",
        "        box-shadow: 2px 2px 10px rgba(0,0,0,0.1);\n",
        "        margin: 10px;\n",
        "    }\n",
        "    .card h3 {\n",
        "        color: #2c3e50;\n",
        "        font-size: 18px;\n",
        "        margin-bottom: 10px;\n",
        "    }\n",
        "    .card p {\n",
        "        font-size: 15px;\n",
        "        color: #333;\n",
        "    }\n",
        "    </style>\n",
        "\"\"\", unsafe_allow_html=True)\n",
        "\n",
        "# -----------------------------\n",
        "# PORTADA\n",
        "# -----------------------------\n",
        "st.title(\"📊 Proyecto de Gestión de Proyectos\")\n",
        "st.subheader(\"Aplicación Educativa con Inteligencia Artificial en Zonas Rurales\")\n",
        "st.markdown(\"**Curso:** Gestión de Proyectos | **Autores:** [Tu Nombre Aquí]\")\n",
        "\n",
        "st.write(\"---\")\n",
        "\n",
        "# -----------------------------\n",
        "# SECCIONES EN MENÚ LATERAL\n",
        "# -----------------------------\n",
        "menu = st.sidebar.radio(\"Ir a:\",\n",
        "    [\"Introducción\", \"Objetivos\", \"Matriz del Proyecto\", \"Cronograma\",\n",
        "     \"Costos\", \"Gestión\", \"Conclusiones\"])\n",
        "\n",
        "# -----------------------------\n",
        "# SECCIONES\n",
        "# -----------------------------\n",
        "if menu == \"Introducción\":\n",
        "    st.header(\"📌 Introducción\")\n",
        "    st.write(\"\"\"\n",
        "    La educación en zonas rurales enfrenta desafíos históricos: limitaciones en conectividad a internet,\n",
        "    carencia de dispositivos tecnológicos, baja capacitación docente en herramientas digitales y desigualdades\n",
        "    en el acceso al conocimiento.\n",
        "\n",
        "    Frente a este panorama, el proyecto busca implementar una **plataforma educativa apoyada en Inteligencia Artificial (IA)**\n",
        "    que permita a estudiantes y docentes de instituciones rurales acceder a análisis de datos educativos,\n",
        "    personalización del aprendizaje y estrategias de enseñanza innovadoras.\n",
        "\n",
        "    Este plan se fundamenta en una gestión estructurada con **cronograma, costos, aseguramiento de calidad y un plan de comunicación**,\n",
        "    con el fin de garantizar sostenibilidad y efectividad en su implementación.\n",
        "    \"\"\")\n",
        "\n",
        "elif menu == \"Objetivos\":\n",
        "    st.header(\"🎯 Objetivos\")\n",
        "    st.subheader(\"Objetivo General\")\n",
        "    st.write(\"\"\"\n",
        "    **Desarrollar e implementar una plataforma educativa con apoyo de Inteligencia Artificial (IA) que fortalezca\n",
        "    la enseñanza y el aprendizaje en zonas rurales, superando las limitaciones de conectividad y acceso tecnológico.**\n",
        "    \"\"\")\n",
        "\n",
        "    st.subheader(\"Objetivos Específicos\")\n",
        "    st.write(\"\"\"\n",
        "    1. Diseñar e implementar un **cronograma estructurado** que contemple fases de diseño, desarrollo, piloto y despliegue, adaptado al contexto rural.\n",
        "    2. Establecer **métricas e indicadores de calidad (KPIs)** para evaluar el impacto de la plataforma en los procesos de enseñanza-aprendizaje.\n",
        "    3. Realizar un **plan de aseguramiento de calidad** mediante pruebas piloto en instituciones rurales, validando la usabilidad y pertinencia de la plataforma.\n",
        "    4. Diseñar un **plan de gestión de personal** que incluya la capacitación docente en el uso de IA y herramientas digitales.\n",
        "    5. Implementar una **estrategia de comunicación** que garantice el acompañamiento y la retroalimentación de los actores educativos (docentes, estudiantes, familias, entidades gubernamentales).\n",
        "    6. Definir un esquema de **control de costos y sostenibilidad financiera** para asegurar la continuidad del proyecto más allá de la fase inicial de implementación.\n",
        "    \"\"\")\n",
        "\n",
        "elif menu == \"Matriz del Proyecto\":\n",
        "    st.header(\"📋 Matriz del Proyecto\")\n",
        "\n",
        "    # Imagen de referencia (tu matriz original)\n",
        "    st.image(\"Educación Zona Rural.jpg\", caption=\"Matriz de referencia del proyecto\", use_column_width=True)\n",
        "\n",
        "    st.write(\"A continuación, se muestra la matriz organizada en recuadros:\")\n",
        "\n",
        "    col1, col2, col3 = st.columns(3)\n",
        "\n",
        "    with col1:\n",
        "        st.markdown('<div class=\"card\"><h3>1. Cronograma</h3><p>Diseño (3 meses)<br>Desarrollo (6 meses)<br>Piloto (4 meses)<br>Despliegue (2 meses)</p></div>', unsafe_allow_html=True)\n",
        "        st.markdown('<div class=\"card\"><h3>6. Estimación de costos</h3><p>Presupuesto detallado con financiación de MinCiencias.</p></div>', unsafe_allow_html=True)\n",
        "        st.markdown('<div class=\"card\"><h3>12. Aseguramiento de calidad</h3><p>Pruebas de rendimiento y análisis de datos iniciales para validar usabilidad.</p></div>', unsafe_allow_html=True)\n",
        "        st.markdown('<div class=\"card\"><h3>18. Control de costos</h3><p>Seguimiento del presupuesto para evitar desviaciones.</p></div>', unsafe_allow_html=True)\n",
        "\n",
        "    with col2:\n",
        "        st.markdown('<div class=\"card\"><h3>7. Definición de métricas</h3><p>KPIs: Precisión del 90% y mejora del 15% en calificaciones.</p></div>', unsafe_allow_html=True)\n",
        "        st.markdown('<div class=\"card\"><h3>13. Adquisición del equipo</h3><p>Formación a docentes y administradores en el uso del dashboard.</p></div>', unsafe_allow_html=True)\n",
        "        st.markdown('<div class=\"card\"><h3>19. Control de calidad</h3><p>Monitoreo de KPIs y ajustes en los modelos de IA según resultados.</p></div>', unsafe_allow_html=True)\n",
        "\n",
        "    with col3:\n",
        "        st.markdown('<div class=\"card\"><h3>8. Gestión de personal</h3><p>Definición de roles: ingeniero de datos, desarrollador, y necesidades de capacitación.</p></div>', unsafe_allow_html=True)\n",
        "        st.markdown('<div class=\"card\"><h3>9. Plan de comunicación</h3><p>Estrategia de reportes de avance y retroalimentación con stakeholders.</p></div>', unsafe_allow_html=True)\n",
        "\n",
        "elif menu == \"Cronograma\":\n",
        "    st.header(\"📅 Cronograma del Proyecto\")\n",
        "\n",
        "    # Datos del cronograma\n",
        "    data = {\n",
        "        \"Fase\": [\"Diseño\", \"Desarrollo\", \"Piloto\", \"Despliegue\"],\n",
        "        \"Inicio\": [\"2025-01-01\", \"2025-04-01\", \"2025-10-01\", \"2026-02-01\"],\n",
        "        \"Fin\":    [\"2025-03-31\", \"2025-09-30\", \"2026-01-31\", \"2026-03-31\"]\n",
        "    }\n",
        "    df = pd.DataFrame(data)\n",
        "\n",
        "    # Crear línea de tiempo con Plotly\n",
        "    fig = px.timeline(\n",
        "        df,\n",
        "        x_start=\"Inicio\",\n",
        "        x_end=\"Fin\",\n",
        "        y=\"Fase\",\n",
        "        color=\"Fase\",\n",
        "        title=\"Cronograma del Proyecto\",\n",
        "        labels={\"Fase\": \"Etapas\"}\n",
        "    )\n",
        "    fig.update_yaxes(autorange=\"reversed\")  # orden visual\n",
        "\n",
        "    st.plotly_chart(fig, use_container_width=True)\n",
        "\n",
        "    st.info(\"\"\"\n",
        "    👉 El cronograma contempla 4 fases principales:\n",
        "    - **Diseño**: 3 meses\n",
        "    - **Desarrollo**: 6 meses\n",
        "    - **Piloto**: 4 meses\n",
        "    - **Despliegue**: 2 meses\n",
        "    \"\"\")\n",
        "\n",
        "elif menu == \"Costos\":\n",
        "    st.header(\"💰 Estimación y Control de Costos\")\n",
        "    st.write(\"\"\"\n",
        "    - Se gestionará financiamiento a través de convocatorias de **MinCiencias**.\n",
        "    - Implementación de un plan de **control de costos** para evitar desviaciones.\n",
        "    \"\"\")\n",
        "\n",
        "elif menu == \"Gestión\":\n",
        "    st.header(\"👥 Gestión del Proyecto\")\n",
        "    st.markdown('<div class=\"card\"><h3>Gestión de personal</h3><p>Asignación de roles y capacitaciones.</p></div>', unsafe_allow_html=True)\n",
        "    st.markdown('<div class=\"card\"><h3>Gestión de comunicación</h3><p>Canales de retroalimentación y reportes de avance.</p></div>', unsafe_allow_html=True)\n",
        "    st.markdown('<div class=\"card\"><h3>Gestión de calidad</h3><p>Pruebas de rendimiento, KPIs y mejoras continuas.</p></div>', unsafe_allow_html=True)\n",
        "\n",
        "elif menu == \"Conclusiones\":\n",
        "    st.header(\"✅ Conclusiones\")\n",
        "    st.success(\"\"\"\n",
        "    El proyecto propone una respuesta integral a las brechas educativas en zonas rurales, integrando tecnología de vanguardia\n",
        "    con un enfoque de gestión de proyectos.\n",
        "\n",
        "    Al contemplar aspectos como cronograma, costos, métricas, gestión de calidad y formación docente, se busca no solo implementar\n",
        "    una plataforma con IA, sino también **garantizar su apropiación por parte de las comunidades educativas rurales**, fomentando así\n",
        "    la equidad en el acceso al conocimiento y mejorando las oportunidades de aprendizaje.\n",
        "    \"\"\")\n"
      ]
    }
  ]
}
!jupyter nbconvert --to script Edu_Zona_Rural.ipynb
