# -*- coding: utf-8 -*-
"""Untitled32.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xISHrVkILZgTw_f1OsW2Za7sI09VWmxZ
"""

import streamlit as st
import pandas as pd
import plotly.express as px

# -----------------------------
# CONFIGURACIÓN DE LA PÁGINA
# -----------------------------
st.set_page_config(page_title="Proyecto Educación Rural con IA", page_icon="📊", layout="wide")

# -----------------------------
# ESTILOS CSS PERSONALIZADOS
# -----------------------------
st.markdown("""
    <style>
    .card {
        background-color: #f9f9f9;
        padding: 20px;
        border-radius: 15px;
        box-shadow: 2px 2px 10px rgba(0,0,0,0.1);
        margin: 10px;
    }
    .card h3 {
        color: #2c3e50;
        font-size: 18px;
        margin-bottom: 10px;
    }
    .card p {
        font-size: 15px;
        color: #333;
    }
    </style>
""", unsafe_allow_html=True)

# -----------------------------
# PORTADA
# -----------------------------
st.title("📊 Proyecto de Gestión de Proyectos")
st.subheader("Aplicación Educativa con Inteligencia Artificial en Zonas Rurales")
st.markdown("**Curso:** Gestión de Proyectos | **Autores:** [Tu Nombre Aquí]")

st.write("---")

# -----------------------------
# SECCIONES EN MENÚ LATERAL
# -----------------------------
menu = st.sidebar.radio("Ir a:",
    ["Introducción", "Objetivos", "Matriz del Proyecto", "Cronograma",
     "Costos", "Gestión", "Conclusiones"])

# -----------------------------
# SECCIONES
# -----------------------------
if menu == "Introducción":
    st.header("📌 Introducción")
    st.write("""
    La educación en zonas rurales enfrenta desafíos históricos: limitaciones en conectividad a internet,
    carencia de dispositivos tecnológicos, baja capacitación docente en herramientas digitales y desigualdades
    en el acceso al conocimiento.

    Frente a este panorama, el proyecto busca implementar una **plataforma educativa apoyada en Inteligencia Artificial (IA)**
    que permita a estudiantes y docentes de instituciones rurales acceder a análisis de datos educativos,
    personalización del aprendizaje y estrategias de enseñanza innovadoras.

    Este plan se fundamenta en una gestión estructurada con **cronograma, costos, aseguramiento de calidad y un plan de comunicación**,
    con el fin de garantizar sostenibilidad y efectividad en su implementación.
    """)

elif menu == "Objetivos":
    st.header("🎯 Objetivos")
    st.subheader("Objetivo General")
    st.write("""
    **Desarrollar e implementar una plataforma educativa con apoyo de Inteligencia Artificial (IA) que fortalezca
    la enseñanza y el aprendizaje en zonas rurales, superando las limitaciones de conectividad y acceso tecnológico.**
    """)

    st.subheader("Objetivos Específicos")
    st.write("""
    1. Diseñar e implementar un **cronograma estructurado** que contemple fases de diseño, desarrollo, piloto y despliegue, adaptado al contexto rural.
    2. Establecer **métricas e indicadores de calidad (KPIs)** para evaluar el impacto de la plataforma en los procesos de enseñanza-aprendizaje.
    3. Realizar un **plan de aseguramiento de calidad** mediante pruebas piloto en instituciones rurales, validando la usabilidad y pertinencia de la plataforma.
    4. Diseñar un **plan de gestión de personal** que incluya la capacitación docente en el uso de IA y herramientas digitales.
    5. Implementar una **estrategia de comunicación** que garantice el acompañamiento y la retroalimentación de los actores educativos (docentes, estudiantes, familias, entidades gubernamentales).
    6. Definir un esquema de **control de costos y sostenibilidad financiera** para asegurar la continuidad del proyecto más allá de la fase inicial de implementación.
    """)

elif menu == "Matriz del Proyecto":
    st.header("📋 Matriz del Proyecto")

    # Imagen de referencia (tu matriz original)
    st.image("Educación Zona Rural.jpg", caption="Matriz de referencia del proyecto", use_column_width=True)

    st.write("A continuación, se muestra la matriz organizada en recuadros:")

    col1, col2, col3 = st.columns(3)

    with col1:
        st.markdown('<div class="card"><h3>1. Cronograma</h3><p>Diseño (3 meses)<br>Desarrollo (6 meses)<br>Piloto (4 meses)<br>Despliegue (2 meses)</p></div>', unsafe_allow_html=True)
        st.markdown('<div class="card"><h3>6. Estimación de costos</h3><p>Presupuesto detallado con financiación de MinCiencias.</p></div>', unsafe_allow_html=True)
        st.markdown('<div class="card"><h3>12. Aseguramiento de calidad</h3><p>Pruebas de rendimiento y análisis de datos iniciales para validar usabilidad.</p></div>', unsafe_allow_html=True)
        st.markdown('<div class="card"><h3>18. Control de costos</h3><p>Seguimiento del presupuesto para evitar desviaciones.</p></div>', unsafe_allow_html=True)

    with col2:
        st.markdown('<div class="card"><h3>7. Definición de métricas</h3><p>KPIs: Precisión del 90% y mejora del 15% en calificaciones.</p></div>', unsafe_allow_html=True)
        st.markdown('<div class="card"><h3>13. Adquisición del equipo</h3><p>Formación a docentes y administradores en el uso del dashboard.</p></div>', unsafe_allow_html=True)
        st.markdown('<div class="card"><h3>19. Control de calidad</h3><p>Monitoreo de KPIs y ajustes en los modelos de IA según resultados.</p></div>', unsafe_allow_html=True)

    with col3:
        st.markdown('<div class="card"><h3>8. Gestión de personal</h3><p>Definición de roles: ingeniero de datos, desarrollador, y necesidades de capacitación.</p></div>', unsafe_allow_html=True)
        st.markdown('<div class="card"><h3>9. Plan de comunicación</h3><p>Estrategia de reportes de avance y retroalimentación con stakeholders.</p></div>', unsafe_allow_html=True)

elif menu == "Cronograma":
    st.header("📅 Cronograma del Proyecto")

    # Datos del cronograma
    data = {
        "Fase": ["Diseño", "Desarrollo", "Piloto", "Despliegue"],
        "Inicio": ["2025-01-01", "2025-04-01", "2025-10-01", "2026-02-01"],
        "Fin":    ["2025-03-31", "2025-09-30", "2026-01-31", "2026-03-31"]
    }
    df = pd.DataFrame(data)

    # Crear línea de tiempo con Plotly
    fig = px.timeline(
        df,
        x_start="Inicio",
        x_end="Fin",
        y="Fase",
        color="Fase",
        title="Cronograma del Proyecto",
        labels={"Fase": "Etapas"}
    )
    fig.update_yaxes(autorange="reversed")  # orden visual

    st.plotly_chart(fig, use_container_width=True)

    st.info("""
    👉 El cronograma contempla 4 fases principales:
    - **Diseño**: 3 meses
    - **Desarrollo**: 6 meses
    - **Piloto**: 4 meses
    - **Despliegue**: 2 meses
    """)

elif menu == "Costos":
    st.header("💰 Estimación y Control de Costos")
    st.write("""
    - Se gestionará financiamiento a través de convocatorias de **MinCiencias**.
    - Implementación de un plan de **control de costos** para evitar desviaciones.
    """)

elif menu == "Gestión":
    st.header("👥 Gestión del Proyecto")
    st.markdown('<div class="card"><h3>Gestión de personal</h3><p>Asignación de roles y capacitaciones.</p></div>', unsafe_allow_html=True)
    st.markdown('<div class="card"><h3>Gestión de comunicación</h3><p>Canales de retroalimentación y reportes de avance.</p></div>', unsafe_allow_html=True)
    st.markdown('<div class="card"><h3>Gestión de calidad</h3><p>Pruebas de rendimiento, KPIs y mejoras continuas.</p></div>', unsafe_allow_html=True)

elif menu == "Conclusiones":
    st.header("✅ Conclusiones")
    st.success("""
    El proyecto propone una respuesta integral a las brechas educativas en zonas rurales, integrando tecnología de vanguardia
    con un enfoque de gestión de proyectos.

    Al contemplar aspectos como cronograma, costos, métricas, gestión de calidad y formación docente, se busca no solo implementar
    una plataforma con IA, sino también **garantizar su apropiación por parte de las comunidades educativas rurales**, fomentando así
    la equidad en el acceso al conocimiento y mejorando las oportunidades de aprendizaje.
    """)
